---
title: "FanficReadR2.0"
output: html_document
---

# Load Packages
```{r}
library(tidyverse)
library(rvest)
library(stringr)
library(xml2)
library(httr)
library(tictoc)
library(ngram)
```


# Helper Functions
```{r}
# Splits strings by a given string valur
strsplits <- function(x, splits, ...)
{
  for (split in splits)
  {
    x <- unlist(strsplit(x, split, ...))
  }
  return(x[!x == ""]) # Remove empty values
}


# Gets work URL from inputted string
WorkURL <- function(x){
  if (grepl("\\/chapters\\/", x )) {
    gsub(
    "\\/chapters\\/[0-9]*", "", x
  )
  } else {
    x
  }
}

WorkInfoURL <- function(input){
  paste0(WorkURL(input), "?view_adult=true")
}

# Gets chapter URL for inputted string
ChapterIndexURL <- function(input){
  paste0(WorkURL(input), "/navigate")
}

# Gets comment page URL for inputted string
CommentURL <- function(input, page){
  paste0(
      WorkURL(input),"?page=",
      page,
      "&show_comments=true&view_adult=true&view_full_work=true#comments"
    )
}

# Downloads HTML page
get_html <- function(input){
  GET(
    input,
    user_agent(
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
    )
  ) |>
    read_html()
}

get_authorname <- function(input){
  get_html(input)|>
    html_elements(css = ".heading") |>
    html_text2() |>
    data.frame() |>
  (\(x) x[6,])() |>
    (\(x) sub(',.*', "", x))()
}
```

# Work Info REGEX Functions
```{r}
get_wordcount <- function(x){
  str_match(x, "Words\\:\\n(.*?)\\\n")[, 2]
}

get_language <- function(x){
  str_match(x, "Language\\:\\n(.*?)\\\n")[, 2]
}

get_chapters <- function(x){
  sub("/.*",
        "",
        str_match(x, "Chapters\\:\\n(.*?)\\\n")[, 2])
}

get_kudos <- function(x){
  str_match(x, "Kudos\\:\\n(.*?)\\\n")[, 2]
}

get_comments <- function(x){
  str_match(x, "Comments\\:\\n(.*?)\\\n")[, 2]
}

get_hits <- function(x){
  str_match(gsub("\n", " ", x), "Hits\\:(.*)")[, 2]
}

get_lastupdated <- function(x){
  str_match(x, "Updated\\:\\n(.*?)\\\n")[, 2]
}

get_completed <- function(x){
  str_match(x, "Completed\\:\\n(.*?)\\\n")[, 2]
}

get_status <- function(x) {
  if ("?" == sub(".*/",
                 "",
                 str_match(x, "Chapters\\:\\n(.*?)\\\n")[, 2])) {
    "Ongoing"
  } else {
    "Complete"
  }
}

get_bookmarks <- function(x){
  str_match(x, "Bookmarks\\:\\n(.*?)\\\n")[, 2]
}

get_relationships <- function(x){
  str_match(gsub("\n", " ", x), "Relationships\\:(.*?)Characters")[, 2]
}

get_warnings <- function(x){
  str_match(x, "Archive Warning\\:\\n(.*?)\\\n")[, 2]
}

get_agecategory <- function(x){
  str_match(x, "Rating\\:\\n(.*?)\\\n")[, 2]
}

get_fandoms <- function(x){
  str_match(gsub("\n", " ", x), "Fandoms\\:(.*?)Relationships")[, 2]
}
```

# Get Work Info
```{r}
GetWorkInfo <- function(input) {
  link <- WorkInfoURL(input)
  work <- get_html(link)
  
  raw_text <- work |>
    html_element(css = ".group") |>
    html_text2()
  
  work_info <- data.frame(matrix(nrow = 1, ncol = 0))
  work_info$word_count <- get_wordcount(raw_text)
  work_info$language <- get_language(raw_text)
  work_info$chapters <- get_chapters(raw_text)
  work_info$kudos <- get_kudos(raw_text)
  work_info$comments <- get_comments(raw_text)
  work_info$hits <- get_hits(raw_text)
  work_info$last_updated <- get_lastupdated(raw_text)
  work_info$completed <- get_completed(raw_text)
  work_info$status <- get_status(raw_text)
  work_info$bookmarks <- get_bookmarks(raw_text)
  work_info$relationships <- get_relationships(raw_text)
  work_info$warnings <- get_warnings(raw_text)
  work_info$age_category <- get_agecategory(raw_text)
  work_info$fandoms <- get_fandoms(raw_text)
  
  return(work_info)
}
```


```{r}
GetWorkInfo("https://archiveofourown.org/works/26587822/chapters/64823242")
```

# CHAPTER INDEX

```{r}
get_chapterurls <- function(x){
  links <- x |>
    html_elements(css = "#main ol a") |>
    html_attr("href") |>
    data.frame()
  
  names(links) <- "url"

  links <- links |>
    mutate(url = paste0("https://archiveofourown.org", url))
  
  links
}
```


```{r}
chapter_getnumber <- function(x){
  str_match(x, "^(.*?)\\.")[, 2]
}

chapter_getdate <- function(x){
  str_match(x, "\\((.*?)\\)$")[, 2]
}

chapter_cleantitle <- function(x) {
  gsub("\\s*\\([^\\)]+\\)", "", 
       gsub("^.*\\.", "", x))
}

```

```{r}
GetChapterInfo <- function(input) {
  index <- get_html(ChapterIndexURL(input))
  
  chapter_info <- index |>
    html_element(css = "#main") |>
    html_text2() |>
    strsplits("\n") |>
    data.frame()
  
  colnames(chapter_info) <- "title"
  
  end <- nrow(chapter_info) - 1
  chapter_info <- chapter_info[2:end, 1] |>
    data.frame()
  
  colnames(chapter_info) <- "title"
  
  chapter_info <- chapter_info |>
    mutate(
      chapter = chapter_getnumber(title),
      date = chapter_getdate(title),
      title = chapter_cleantitle(title)
    )
  
  
  links <- get_chapterurls(index)
  links$wordcount <- 0
  
  for (i in 1:nrow(links)) {
    url <- paste0(links[i, 1], "?view_adult=true")
    wordcount <- get_html(url) |>
      html_element(css = "div.userstuff.module") |>
      html_text2() |>
      str_replace_all("\\n", " ") |>
      wordcount()
    links[i, 2] <- wordcount
  }
  
  chapter_info <- cbind(chapter_info, links)
  
  chapter_info
}
```


```{r}
GetChapterInfo("https://archiveofourown.org/works/26587822")
```



## COMMENTS

```{r}
comments_getuser <- function(x) {
  gsub(" ", "", str_match(x, "(.*)on Chapter")[, 2])
}

comments_getchapter <- function(x) {
  str_match(x, "on Chapter +(.*?) +")[, 2]
}

comments_getdate <- function(x, y) {
  str_match(x, paste0("on Chapter ", y,  " +(.*?)\\\n"))[, 2]
}

comments_gettext <- function(x, y) {
  str_match(gsub("\n", " ", x),
            paste0(y, "(.*?)Comment Actions"))[, 2]
}
```


```{r}
GetComments <- function (input) {
  
  ### Placeholder DF to store results
  comment_data <- matrix(ncol = 4, nrow = 1) |>
    data.frame() |>
    rename(
      user = X1,
      chapter = X2,
      date = X3,
      text = X4
    )
  
  
  for (i in 1:1000) {
    url <- CommentURL(input, i)
    comm <- get_html(url)
    
    comments <- comm |>
      html_elements(css = "ol li") |>
      html_text2() |>
      data.frame()
    
    names(comments) <- "comments"
    
    if (0 ==
        comments |>
        filter(grepl("on Chapter", comments)) |>
        nrow()) {
      break
    }
    else{
      
      names(comments) <- "comments"
      
      ### Extracts user, chapter, date, and text of comment
      comments <- comments |>
        filter(grepl("on Chapter", comments)) |>
        mutate(user = comments_getuser(comments)) |>
        mutate(chapter = comments_getchapter(comments)) |>
        mutate(date = comments_getdate(comments, chapter)) |>
        mutate(text = comments_gettext(comments,date)) |>
        select(-comments) |>
        distinct(text, .keep_all = TRUE) ### Removes duplicates
      
      
      comment_data <- rbind(comment_data, comments)
    }
  }
  
  ### Get Authors Name
  name <- comm |>
    html_elements(css = ".heading") |>
    html_text2() |>
    data.frame()

  name <- name[6,]
  
  ### Flag comments made by the author
  comment_data <- comment_data[-1, ] #|>
   #mutate(author = as.character(str_detect(name, user)))
  
  comment_data[-1, ]
  
}


#GetComments("https://archiveofourown.org/works/5214230/chapters/12021212")
```








## AUTHOR INFO

```{r}
Author_Name <- function(input) {
  if (grepl("https://archiveofourown.org/users", input, fixed = FALSE)) {
    strsplit(gsub("https://archiveofourown.org/users/", "", input),
             "[/]")[[1]][1]
    
  } else {
    if (grepl("https://archiveofourown.org/", input, fixed = FALSE)) {
      print("Please enter a valid AO3 user profile link OR user name")
      
    } else{
      input
    }
  }
  
}

get_profileurl <- function(x) {
  paste0("https://archiveofourown.org/users/",
         Author_Name(x),
         "/profile")
}

get_worksurl <- function(x) {
  paste0("https://archiveofourown.org/users/",
         Author_Name(x),
         "/works")
}

get_authorprofile <- function(x){
  get_html(get_profileurl(x))
}

get_authorworks <- function(x){
  get_html(get_worksurl(x))
}

get_joindate <- function(x) {
  sub(".*I joined on *(.*?) *My user.*", 
      "\\1", gsub("\n", " ",
           gsub("[[:punct:]]", "", x)))
}

get_userid <- function(x) {
  str_extract(gsub("\n", " ",
                   gsub("[[:punct:]]", "", x)), "My user ID is*.+") |>
    str_replace("My user ID is ", "")
}

get_workscount <- function(x) {
  sub(".*Works *(.*?) *Series.*", "\\1",
      gsub(
        "\n",
        " ",
        gsub(
          "[[:punct:]]",
          "",
          x |>
            html_element(css = "#dashboard") |>
            html_text2()
        )
      ))
}

get_bookmarkscount <- function(x) {
  sub(".*Bookmarks *(.*?) *Collections.*",
      "\\1",
      gsub(
        "\n",
        " ",
        gsub(
          "[[:punct:]]",
          "",
          x |>
            html_element(css = "#dashboard") |>
            html_text2()
        )
      ))
}

get_bookmarksurl <- function(x){
      paste0("https://archiveofourown.org/users/",
           Author_Name(x),
           "/bookmarks")
}
```




```{r}
GetAuthorInfo <- function(input) {
  ### Setup Author Info Table
  author_info <- data.frame(matrix(ncol = 8, nrow = 1)) 
  
  names(author_info) <- c(
    "Name",
    "ID",
    "JoinDate",
    "ProfileURL",
    "NumberWorks",
    "WorksURL",
    "NumberBookmarks",
    "BookmarksURL"
  )
  

  ### Download Profile HTML Page
  author_profile <- get_authorprofile(input)
  
  profile <- author_profile |>
    html_element(css = ".meta") |>
    html_text2()

  author_info$Name <- Author_Name(input)
  author_info$ID <- get_userid(profile)
  author_info$JoinDate <- get_joindate(profile)
  author_info$ProfileURL <- get_profileurl(input)
  author_info$NumberWorks <- get_workscount(author_profile)
  author_info$WorksURL <- get_worksurl(input)
  author_info$NumberBookmarks <- get_bookmarkscount(author_profile)
  author_info$BookmarksURL <- get_bookmarksurl(input)
  
  author_info
}
```


```{r}
GetAuthorInfo("https://archiveofourown.org/users/Christy_Muse_Pcjax/pseuds/Christy_Muse_Pcjax")
```

```{r}
get_workstable <- function(x){
  sub(".*.Listing Works",
        "",
        gsub(
          "",
          "",
          x |>
            html_element(css = "#main") |>
            html_text2()
        )) |>
    str_match_all("\\\n(.*?)by do not cache") |>
    data.frame() |>
    select(X2) |>
    rowid_to_column() |>
    rename(Titles = X2, Work = rowid)
}

get_hits_alt <- function(x){
  str_match(x, "Hits\\:\\n(.*?)\\\n")[1, 2]
}

get_lastupdated_alt <- function(x){
  str_match(x, "\\n(.*?)\\\n\\nTags")[1, 2]
}

get_status_alt <- function(x) {
  str_match(x,paste0("\\n(.*?)\\\n\\n", 
                     get_lastupdated_alt(x)))[1, 2]
}

get_relationships_alt <- function(x) {
  str_match(x,paste0("\\n(.*?)\\\n", 
                     get_status_alt(x)))[1, 2]
}

get_warnings_alt <- function(x){
  str_match(x,paste0("\\n(.*?)\\\n", 
                     get_relationships_alt(x)))[1, 2]
}

get_category_alt <- function(x){
          str_match(x, paste0("\\n(.*?)\\\n", 
                              get_warnings_alt(x)))[1, 2]
}

get_fandoms_alt <- function(x) {
  str_match(x,paste0("\\nFandoms\\:(.*?)\\\n", 
                     get_category_alt(x)))[1, 2]
}

check_if_noworks <- function(x){
  0 == sub(".*Works *(.*?) *Series.*", "\\1",
               gsub(
                 "\n",
                 " ",
                 gsub(
                   "[[:punct:]]",
                   "",
                   x %>%
                   html_element(css = "#dashboard") %>%
                   html_text2()
                 )
               ))
}
```

```{r}
GetAuthorWorks <- function(input) {
  author_works <- get_html(get_worksurl(input))
  works_info <- get_workstable(author_works)
  
  if (check_if_noworks(author_works)) {
    "N/A"
  }
  else{
  
  
  works_info$raw_text <- strsplits(author_works %>%
                                     html_element(css = "#main") %>%
                                     html_text2(),
                                   works_info$Titles)[-1]
  
  
  ### Get Works IDs and URLs
  works_ids <- author_works %>%
    html_elements(css = "h4 a") %>%
    html_attr("href") %>%
    data.frame()
  
  colnames(works_ids) <- "works_ids"
  
  works_ids <- works_ids %>%
    filter(grepl("/works/", works_ids)) %>%
    mutate(works_ids = gsub("/works/", "", works_ids))
  
  works_info$work_id <- works_ids$works_ids
  
  
  ### Get Works URLs
  works_info$work_url <-paste0("https://archiveofourown.org/works/", 
                               works_info$work_id)
  
  for (i in 1:nrow(works_info)) {
    raw_text <- works_info$raw_text[i]
    works_info$word_count[i] <- get_wordcount(raw_text)
    works_info$language[i] <- get_language(raw_text)
    works_info$chapters[i] <- get_chapters(raw_text)
    works_info$kudos[i] <- get_kudos(raw_text)
    works_info$comments[i] <- get_comments(raw_text)
    works_info$hits[i] <- get_hits_alt(raw_text)
    works_info$last_updated[i] <- get_lastupdated_alt(raw_text)
    works_info$status[i] <- get_status_alt(raw_text)
    works_info$bookmarks[i] <- get_bookmarks(raw_text)
    works_info$pairings[i] <- get_relationships_alt(raw_text)
    works_info$warnings[i] <- get_warnings_alt(raw_text)
    works_info$age_category[i] <- get_category_alt(raw_text)
    works_info$fandoms[i] <- get_fandoms_alt(raw_text)
  }
  
  works_info |>
    select(-raw_text)
  
  }
}



GetAuthorWorks("https://archiveofourown.org/users/Christy_Muse_Pcjax/pseuds/Christy_Muse_Pcjax")
```


# WORKS INDEX


```{r}
get_indexURL <- function(input) {
  paste0(
    "https://archiveofourown.org/tags/",
    str_replace_all(
      str_replace_all(input, " ", "%20"), "\\.", "*d*"),
    "/works"
  )
}

get_indexURLpage <- function(input, page) {
  paste0(input, "?page=", page)
}

get_indexpages <- function(input) {
  input |>
    html_element(css = "ol.pagination.actions") |>
    html_text2() |>
  str_match("\\n(.*?)\\nNext") |>
  (\(x) x[,2])() |>
  as.numeric()
}

get_pageworkIDs <- function(input){
  input |>
  html_elements(css = "ol.work.index.group") |>
  as.character() |>
  str_match_all("<li id=(.*?) class=") |>
  data.frame() |>
  select("X2") |>
  mutate(X2 = gsub('[[:punct:]]', "", X2),
         X2 = gsub("work", "", X2)) |>
  rename(id = X2) |>
    mutate(id = as.numeric(id), 
           id = paste0("https://archiveofourown.org/works/", id))
}

```


```{r}
GetFandomIndex <- function(fandom, pages) {
  indexURL <- get_indexURL(fandom)
  index <- get_html(indexURL)
  indexpages <- get_indexpages(index)
  
  pagecount <- min(pages, indexpages)
  
  index_ids <- as.data.frame(matrix(ncol = 1, nrow = 0))
  
  for (i in 1:pagecount){
    pageURL <- get_indexURLpage(indexURL, i)
    
    page_html <- get_html(pageURL)
    
    id_list <- get_pageworkIDs(page_html)
    
    index_ids <- rbind(index_ids, id_list)
  }
  
  index_ids
}
```


```{r}
test <- "Harry Potter - J. K. Rowling"
GetFandomIndex(test, 2)
```

# TIE TOGETHER

```{r}
test <- "Harry Potter - J. K. Rowling"
test_index <- get_fandom_index(test, 2)
```

```{r}
test_work <- test_index[4,]

test_comments <- GetComments(test_work)


```

```{r}
GetWorkInfo(test_work)
```
```{r}
GetChapterInfo(test_work)
```

```{r}
test_name <- get_authorname(test_work)
```

```{r}
GetAuthorInfo(test_name)
GetAuthorWorks(test_name)
```


```{r}
GetFullData <- function(fandom, pages){
  
  output_list <- list()
  
  works_index <- GetFandomIndex(fandom, pages)
  
  for (i in 1:nrow(works_index)){
    temp_work <- works_index[i,]
    temp_name <- get_authorname(temp_work)
    temp_authorinfo <- GetAuthorInfo(temp_name)
    #temp_authorworks <- GetAuthorWorks(temp_name)
    #print("author works gotten")
    temp_workinfo <- GetWorkInfo(temp_work)
    temp_chapterinfo <- GetChapterInfo(temp_work)
    temp_comments <- GetComments(temp_work)
    
    temp_list <- list(
      work = temp_work,
      name = temp_name,
      authorinfo = temp_authorinfo,
      #authorworks = temp_authorworks,
      workinfo = temp_workinfo,
      chapterinfo = temp_chapterinfo,
      comments = temp_comments
    )
    
    output_list[[i]] <- temp_list
    
    Sys.sleep(60)
    
  }
  
  output_list
}
```


```{r}
GetFullData("Harry Potter - J. K. Rowling", 1)
```
# TEST CASE: https://archiveofourown.org/users/Remyroo17/pseuds/Remyroo17/works

```{r}
test <- "https://archiveofourown.org/works/22821859"

name <- get_authorname(test)
GetAuthorInfo(name)
GetAuthorWorks(name)
```

