---
title: "WorksInfoTest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE, warning  = FALSE}
library(tidyverse)
library(rvest)
library(stringr)
library(xml2)
library(httr)
```



```{r}
## Bespoke Stringsplitting function
strsplits <- function(x, splits, ...)
{
  for (split in splits)
  {
    x <- unlist(strsplit(x, split, ...))
  }
  return(x[!x == ""]) # Remove empty values
}
```

# WorkURL
```{r}
WorkURL <- function(x){

if (grepl("\\/chapters\\/", x )) {
  gsub(
  "\\/chapters\\/[0-9]*", "", x
)
} else {
  x
}
}
```

## Get Work Info
```{r}

GetWorkInfo <- function(input) {
  work <- GET(
    WorkURL(input),
    user_agent(
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
    )
  ) %>%
    read_html()
  
  raw_text <- work %>%
    html_element(css = ".group") %>%
    html_text2()
  
  work_info <- data.frame(matrix(nrow = 1, ncol = 0))
  
  ### Word Count
  work_info$word_count <-
    str_match(raw_text, "Words\\:\\n(.*?)\\\n")[, 2]
  
  ### Language
  work_info$language <-
    str_match(raw_text, "Language\\:\\n(.*?)\\\n")[, 2]
  
  ### Chapter Count
  work_info$chapters <-
    sub("/.*",
        "",
        str_match(raw_text, "Chapters\\:\\n(.*?)\\\n")[, 2])
  
  ### Kudos Count
  work_info$kudos <-
    str_match(raw_text, "Kudos\\:\\n(.*?)\\\n")[, 2]
  
  ### Comments Count
  work_info$comments <-
    str_match(raw_text, "Comments\\:\\n(.*?)\\\n")[, 2]
  
  ### Hits Count
  work_info$hits <-
    str_match(gsub("\n", " ", raw_text), "Hits\\:(.*)")[, 2]
  
  ### Last Updated
  work_info$last_updated <-
    str_match(raw_text, "Updated\\:\\n(.*?)\\\n")[, 2]
  
  ### Completed
  work_info$completed <-
    str_match(raw_text, "Completed\\:\\n(.*?)\\\n")[, 2]
  
  ### (In)Complete Status
  work_info$status <- if ("?" == sub(".*/",
                                     "",
                                     str_match(raw_text, "Chapters\\:\\n(.*?)\\\n")[, 2])) {
    "Ongoing"
  } else {
    "Complete"
  }
  
  ### Bookmarks Count
  work_info$bookmarks <-
    str_match(raw_text, "Bookmarks\\:\\n(.*?)\\\n")[, 2]
  
  ### Relationships
  work_info$relationships <-
    str_match(gsub("\n", " ", raw_text), "Relationships\\:(.*?)Characters")[, 2]
  
  ### Content Warnings
  work_info$warnings <-
    str_match(raw_text, "Archive Warning\\:\\n(.*?)\\\n")[, 2]
  
  ### Age Category (Mature, Teens, General)
  work_info$age_category <-
    str_match(raw_text, "Rating\\:\\n(.*?)\\\n")[, 2]
  
  ### Fandoms
  work_info$fandoms <-
    str_match(gsub("\n", " ", raw_text), "Fandoms\\:(.*?)Relationships")[, 2]
  
  ### Display the work info table
  work_info
}

#GetWorkInfo("https://archiveofourown.org/works/28747785")
```

## Chapter Index
```{r}
GetChapterIndex <- function(input){
index <- GET(
    paste0(WorkURL(input), "/navigate"),
    user_agent(
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
    )
  ) %>%
    read_html() 

## Get Chapter names, numbers, and dates

chapter_info <- index %>%
  html_element(css = "#main") %>%
  html_text2() %>%
  strsplits("\n") %>%
  data.frame() 

colnames(chapter_info) <- "title"

end <- nrow(chapter_info) - 1
chapter_info <- chapter_info[2:end,1] %>% data.frame()

colnames(chapter_info) <- "title"

chapter_info <- chapter_info %>% 
  mutate(title = paste0("START", title, "END")) %>% ### adding markers for start/end
  mutate(
    chapter = str_match(title, "START(.*?)\\.")[, 2],
    date = str_match(title, "\\((.*?)\\)END")[, 2]
  ) ### extracting chapter number and date

  
for (i in 1:nrow(chapter_info)){
  chapter_info[i,1] <- gsub(paste0("START", chapter_info[i,2], "."), "", chapter_info[i,1])
  chapter_info[i,1] <- gsub(paste0("\\(", chapter_info[i,3], "\\)END"), "", chapter_info[i,1])
}

### Get Chapter URLS

links <- index %>%
  html_elements(css = "#main ol a") %>%
  html_attr("href") %>%
  data.frame() 

names(links) <- "url"

links <- links %>%
  mutate(url = paste0("https://archiveofourown.org", url))

chapter_info <- cbind(chapter_info, links)

chapter_info

}
#GetChapters("https://archiveofourown.org/works/28747785")
```


## Get Comments
```{r}
GetComments <- function (input, keep.text = TRUE, excl.author = FALSE){
  
### Placeholder DF to store results
comment_data <- matrix(ncol = 4, nrow = 1) %>%
  data.frame() %>%
  rename(
    user = X1,
    chapter = X2,
    date = X3,
    text = X4
  )


for (i in 1:100) {
  
  ### loops through each comment page
  url <-
    paste0(
      WorkURL(input),"?page=",
      i,
      "&show_comments=true&view_adult=true&view_full_work=true#comments"
    )
  
  ### Gets HTML page
  comm <- GET(
    url,
    user_agent(
      "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36"
    )
  ) %>%
    read_html()
  
  ### Downloads comments
  test_comm <-  comm %>%
    html_elements(css = "ol li") %>%
    html_text2() %>%
    data.frame()
  
  names(test_comm) <- "comments"
  
  ### Checks if comments are there - if not, breaks the loop
  if (0 ==
      test_comm %>%
      filter(grepl("on Chapter", comments)) %>%
      nrow()) {
    break
  } 
  else{

### Get Comments
    comments <- test_comm
    
    names(comments) <- "comments"
    
    ### Extracts user, chapter, date, and text of comment
    comments <- comments %>%
      filter(grepl("on Chapter", comments)) %>%
      mutate(user = gsub(" ","", str_match(comments, "(.*)on Chapter")[, 2])) %>%
      mutate(chapter = str_match(comments, "on Chapter +(.*?) +")[, 2]) %>%
      mutate(date = str_match(comments, paste0("on Chapter ", chapter,  " +(.*?)\\\n"))[, 2]) %>%
      mutate(text = str_match(
        gsub("\n", " ", comments),
        paste0(date, "(.*?)Comment Actions")
      )[, 2]) %>%
      select(-comments) %>%
      distinct(text, .keep_all = TRUE) ### Removes duplicates
      
    
    comment_data <- rbind(comment_data, comments)
    
    ### Sys.sleep command so that AO3 isn't overloaded
    Sys.sleep(2)
  }
}



### Get Authors Name
name <- comm %>%
  html_elements(css = ".heading") %>%
  html_text2() %>%
  data.frame()

name <- name[6, ]

### Flag comments made by the author
comment_data <- comment_data[-1,] %>%
  mutate(author = ifelse(user == name, 1, 0))

### Adds option to ignore author responses
if(excl.author == TRUE){
  comment_data <- comment_data %>%
    filter(author == 0) %>%
    select(-author)
} 

### Comments eat up space, so if you're interested in counts, then this
### parameter lets you not store the text of comments

if (keep.text == FALSE){
  
  comment_data %>%
  select(-text)
  
} else{
  
  comment_data
  
}


}

#GetComments(input = "https://archiveofourown.org/works/28747785", keep.text = FALSE, excl.author = TRUE)
```


# TESTING AREA

## GetWorkInfo

Results should be: a 1x13 table

### From a Chapter Link
```{r}
GetWorkInfo("https://archiveofourown.org/works/30422667/chapters/75006909")
```

### From a Work Link
```{r}
GetWorkInfo("https://archiveofourown.org/works/30422667")
```

## GetChapterIndex

### From a Chapter Link
```{r}
GetChapterIndex("https://archiveofourown.org/works/30422667/chapters/75006909")
```

### From a Works Link
```{r}
GetChapterIndex("https://archiveofourown.org/works/30422667")
```

## Get Comments

### From a Chapter Link
```{r}
GetComments(input = "https://archiveofourown.org/works/28747785/chapters/70490640", keep.text = FALSE, excl.author = FALSE)
```


### From a Works Link
```{r}
GetComments(input = "https://archiveofourown.org/works/28747785", keep.text = FALSE, excl.author = FALSE)
```
